# Generated by Django 3.1 on 2020-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(default="2012-02-03"),
            preserve_default=False,
        ),
    ]
