# Generated by Django 3.1 on 2020-08-16 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='ETA_Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='TO_Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
